Сделал
Darkside1608/JavaSIS-3.20 pull request #2
Opened 2020-03-11 14:59 UTC by Darkside1608

2020-03-12 01:54 UTC, Bael requested changes
В целом вы молодец, просьба поправить нанесение урона и замечания по параметрам, после чего проверю еще раз.

2020-03-12 01:54 UTC, Bael commented on unit2/homework/src/main/java/pro/it/sis/javacourse/Damage.java
> +    Damage (int p, int f, int i) {
зачем модификатор доступа по умолчанию?

2020-03-12 01:54 UTC, Bael commented on unit2/homework/src/main/java/pro/it/sis/javacourse/Damage.java
> +        physicalDamage = p;
рекомендуется давать параметрам осмысленные имена, здесь параметр можно сделать physicalDamage 
чтобы присвоить полю объекта значение можно сделать this.physicalDamage  = physicalDamage 
так же параметры можно объявить как final, чтобы случайно не пытаться присвоить параметру значение

2020-03-12 01:54 UTC, Bael commented on unit2/homework/src/main/java/pro/it/sis/javacourse/Target.java
> +        physicalDamage = p;
урон надо накапливать. Если по цели ударят несколько раз - вы сохраните только последний урон.

2020-03-12 01:54 UTC, Bael commented on unit2/homework/src/main/java/pro/it/sis/javacourse/Weapon.java
> +    public Weapon (String name, int p, int f,int i){
то же самое, старайтесь давать осмысленные имена  параметрам. Потом будет сложно подавать аргументы не перепутав.

2020-03-12 01:54 UTC, Bael commented on unit2/homework/src/test/java/pro/it/sis/javacourse/WeaponTest.java
> +   public static void main(String[] args){
тест не обязан быть public static void main, более того аннотация @Test будет конфликтовать с main методом. (при попытке запуска всех тестов в классе вы запустите только main метод)

2020-03-25 14:49 UTC, pavelsilent commented
Напоминаю, что это задание пока не принято. Прочитайте замечания.

2020-03-25 15:50 UTC, Darkside1608 commented
Я знаю. Как мне правильно сделать что бы исправления отобразились я в свою ветку по unit 1 уже давно закинул исправления но они не отображаются в пулле

2020-03-25 16:28 UTC, pavelsilent commented
> Я знаю. Как мне правильно сделать что бы исправления отобразились я в свою ветку по unit 1 уже давно закинул исправления но они не отображаются в пулле

Можете просто прислать ссылку на соответствующие коммиты.

2020-04-02 01:30 UTC, Bael approved these changes
вы поправили урон, отлично. задание принято
Старайтесь использовать автоформатирование идеи, и не делайте слишком много пустых строк, выглядит не всегда к месту.

2020-04-07 12:19 UTC, closed without merging